// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDEB6f7zl2SH5ihJ_w4B3NdxPN596amHs',
    appId: '1:973866897638:web:a12040f0bce0d8da0fab27',
    messagingSenderId: '973866897638',
    projectId: 'v2g-app-502c0',
    authDomain: 'v2g-app-502c0.firebaseapp.com',
    storageBucket: 'v2g-app-502c0.firebasestorage.app',
    measurementId: 'G-8R7FHFN8MX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKdWns1-IGZQh4rb1eJHMOM14Job3DvdU',
    appId: '1:1062916283143:android:d633577c11861bbc3783a2',
    messagingSenderId: '1062916283143',
    projectId: 'finalyearproject-4f1ea',
    storageBucket: 'finalyearproject-4f1ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtZeQqH2CFH6vPBsCBKJCk7e42myci3mE',
    appId: '1:1062916283143:ios:89ff2365522e6c803783a2',
    messagingSenderId: '1062916283143',
    projectId: 'finalyearproject-4f1ea',
    storageBucket: 'finalyearproject-4f1ea.firebasestorage.app',
    iosBundleId: 'com.example.v2gApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9gZWdLnNQ9Z0e8baPo898tAOC-Cq99qI',
    appId: '1:973866897638:ios:c8b4df01503499850fab27',
    messagingSenderId: '973866897638',
    projectId: 'v2g-app-502c0',
    storageBucket: 'v2g-app-502c0.firebasestorage.app',
    iosBundleId: 'com.example.v2gApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDEB6f7zl2SH5ihJ_w4B3NdxPN596amHs',
    appId: '1:973866897638:web:1888e70eda9363fa0fab27',
    messagingSenderId: '973866897638',
    projectId: 'v2g-app-502c0',
    authDomain: 'v2g-app-502c0.firebaseapp.com',
    storageBucket: 'v2g-app-502c0.firebasestorage.app',
    measurementId: 'G-236Y587FNF',
  );
}